sudo: required
language: java
jdk:
  - openjdk11
before_install:
  - openssl aes-256-cbc -K $encrypted_075df4eec6b6_key -iv $encrypted_075df4eec6b6_iv -in travis/codesigning.asc.enc -out travis/codesigning.asc -d
  - rm "${JAVA_HOME}/lib/security/cacerts"
  - ln -s /etc/ssl/certs/java/cacerts "${JAVA_HOME}/lib/security/cacerts"
script:
  - ./mvnw clean install
  - |
    set -e
    if [ "$TRAVIS_BRANCH" = 'master' ] && [ "$TRAVIS_PULL_REQUEST" == 'false' ]; then
       echo "Importing GPG key into keyring"
       gpg --fast-import travis/codesigning.asc

       echo "Setting release version"
       ./scripts/set-maven-version.sh

       echo "Running release"
       ./mvnw --settings travis/settings.xml deploy -Prelease -DskipTests=true
    fi
env:
  global:
    - GPG_KEY_NAME=navikt
    - OSSRH_JIRA_USERNAME=navikt
    - secure: ueGi42U6ZYQ+wsERFdSV8eDrDmGZT77jQIW3qKTZ4veDfRY9sKjgnrs//E3Qd0896WFPUZAPzeNxXWyFokwgcDVweqPi+UNAA25r6DUSiVhw/cwyAOvEnzGfvY83EWcfu00ad00ZId3+clHPGhCaieKoNO+32p+j1KRuZzLRBkn1rlUP9WONTv4Wnx9Q586fuVabcXsK/B6HWsQwq/IKkgXsdh1rilY9+0AUKbZy4RLfPWRKgRF+YDneAlFH55cacHAldr6WHJ2OaTX6ELo4ZIIFP36KTNMvxbQMwKb/MNbTdGKuCpPwcNzaZ3Qf2pR7RYL3gL9afVNoTX/ECSZtBlBu0TnRHPlGB1kXLTDfuSkz3Lh/ZDa7nlaxMYL2hejKfseRZuSw9H9UstpL6axI8+j+MwUP2FHep72J3LZKzFpLtmz5LPhajSw5o9VeaFj4xyTK62Wxj3xmkuRXoz0HbKheh6dK6llhPQS99S1aTCloT9DFRvhBazaNKCkapLRytETsd1VQW5Gu5usVlmeKubEo7eKYAqjezuDjUrh8AOfTtEzAeSc2fdxqEaIXzpsko1afmI1qjwAS4zlyFvJ3S41kvgZaOFaF/fMOpP1R76pbPY/UOdgloUEZdbg83x6ZhxQEyOFsR/hWvAWm77I7RTmXHjkNPseuzibornCOH80=
    - secure: avb09BBEkVAEpqolGFJ5SJgOkCv9cS08lL6/k20bvpOW0ancS8XCJ6Mh2gC1YWNadmSkJzUmbKLiZFWYvIrgCqYG648lRkVpxASIy0uwBiB+Q19+W6VKqf8w7uQTAHzMVwV6V1tXrtvPRILbLl3JAsfjwI2MkmOqk9gbOlR3vQTPCt0iwWfWnrRnpUBKneXZ+32bdD8UIuvJA85wXRH642NazqxmCS6QJ0LnKntcFdgB4VOypppymcwttvxSrG1Aek4HlTZ+ZGiynwBSV8n20/SU+4E29oyDrw/FFEK5lNYsh9G4+cOiNcq16JvMAWtGvFgzXTtsioU/00leJ/2aitInghCL4Mgf/CooJKjMP9ktihwNKFkWAtOqnArOEKiXKywVCeMJZzJbujhYpalac9/79LMGKHDxgT25IU3TVWr2JH/ZoqelSfZCHnZdRNtnanLNxnvm/+GTGiG5hhxvr1g+DKLtdxGmvH71Mvpjzzb3caLrFVI3oT/o4F91VL2tTvHalHPjBUUWuaKE7SIdNomTc60LnoSIwzk4VmNIEQ9745xRuGOzFoLQv2ygDOboF5OOINtO9YmBIxO+ArgDXlZ1yNQA063BDu0mVbiBAuNuSFAhQcnx4X62lcXgnyaYbfJv6fQFxG3kVoyQeWEoUU6OEG/uA8P2uA/lrBfhiqM=