sudo: required
language: java
jdk:
  - openjdk11
before_install:
  - openssl aes-256-cbc -K $encrypted_033a38c09167_key -iv $encrypted_033a38c09167_iv
    -in travis/codesigning.asc.enc -out travis/codesigning.asc -d
  - rm "${JAVA_HOME}/lib/security/cacerts"
  - ln -s /etc/ssl/certs/java/cacerts "${JAVA_HOME}/lib/security/cacerts"
script:
  - ./mvnw clean install
  - |
    set -e
    if [ "$TRAVIS_BRANCH" = 'master' ] && [ "$TRAVIS_PULL_REQUEST" == 'false' ]; then
       echo "Importing GPG key into keyring"
       gpg --fast-import travis/codesigning.asc

       echo "Setting release version"
       ./scripts/set-maven-version.sh

       echo "Running release"
       ./mvnw --settings travis/settings.xml deploy -Prelease -DskipTests=true
    fi
env:
  global:
    - GPG_KEY_NAME=navikt
    - OSSRH_JIRA_USERNAME=navikt
    - secure: todo
    - secure: todo