name: Maven Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '11.x'
      - name: Set version
        run: ./scripts/set-maven-version.sh
      - name: Test and build
        run: ./mvnw clean install
      - name: Upload artifact
        run: ./mvnw --settings .github/settings.xml deploy -X -DskipTests=true
        env:
          GITHUB_USERNAME: x-access-token
          GITHUB_PASSWORD: ${{ secrets.GITHUB_ACCESS_TOKEN }}